apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-openshift-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: python-openshift-app

  template:
    metadata:
      labels:
        app: python-openshift-app

    spec:
      containers:
      - name: python-openshift-app
        image: python-openshift-app:latest

        ports:
        - containerPort: 8080
